require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# add before target 'xxxx' do
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
platform :ios, '12.0'

target 'onebestlife' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true

  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'onebestlifeTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })
  post_install do |installer|
    flipper_post_install(installer)
    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
              "  atomic_notify_one(state);", "  folly::atomic_notify_one(state);")
    react_native_post_install(installer)
  end
end
